name: create-release-on-push-master

on:
    push:
        branches:
            - master
            - dev

jobs:
    create-release:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.6

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "20.13.1"

            - name: Install dependencies
              run: npm i

            - name: Pack production build
              id: pack
              run: |
                  npm_pack_output=$(npm pack --json)
                  echo "npm_pack_output<<EOF" >> $GITHUB_OUTPUT
                  echo "$npm_pack_output" >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Get pack file name
              id: packagefilename
              run: |
                  echo "${{ steps.pack.outputs.npm_pack_output }}" | grep "filename" | awk -F': ' '{print $2}' | awk -F',' '{print $1}' | awk '{print "\"" $0 "\""}' >> $GITHUB_OUTPUT

            - name: Unpack production pack
              run: tar -xvf "${{ steps.packagefilename.outputs.packfilename }}.tgz -C package"

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.event.head_commit.message }}
                  release_name: ${{ github.event.head_commit.message }}
                  body: |
                      <!--- RELEASE DRAFT FROM ${{ github.event.head_commit.message }}

                      Checklist:
                      - The release tag and name is correct (follows the semantic versionning convention),
                      - The asset ZIP file contains all and only the files that the package needs,
                      - The changelog is filled.

                      -->

                      # CHANGELOG - ${{ github.event.head_commit.message }} (${{ github.sha }})

                      - ...
                  draft: true
                  prerelease: false

            - name: Add assets to release
              uses: dwenegar/upload-release-assets@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  release_id: ${{ steps.create_release.outputs.id }}
                  assets_path: package
