name: pretty-on-push
on:
    push:
        branches:
            - dev

jobs:
    pretty:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.6

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Run pretty script
              run: npm run pretty

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              with:
                  commit: --signoff
                  default_author: user_info
                  message: "[ACTIONS] Pretty repo on push"
