name: Pretty on push dev

on:
    push:
        branches:
            - dev

permissions:
    actions: write
    contents: write

jobs:
    pretty:
        name: Pretty
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.6

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "20.13.1"

            - name: Install dependencies
              run: npm ci

            - name: Run pretty script
              run: npm run pretty

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              with:
                  author_name: $ACTIONS_COMMIT_USER_NAME
                  author_email: $ACTIONS_COMMIT_USER_EMAIL
                  message: "[ACTIONS] Pretty repo on push dev"
