name: Pretty on push dev

on:
    push:
        branches:
            - dev

permissions:
    contents: write

jobs:
    pretty:
        name: Pretty
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "20.13.1"

            - name: Install dependencies
              run: npm ci

            - name: Ignore Github Action workflows
              run: |
                  echo "\n.github/workflows" >> .prettierignore

            - name: Run pretty script
              run: |
                  npm run pretty

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              with:
                  author_name: ${{ env.ACTIONS_COMMIT_USER_NAME }}
                  author_email: ${{ env.ACTIONS_COMMIT_USER_EMAIL }}
                  message: "[ACTIONS] Pretty repo on push dev"


                  