name: Publish on release

on:
    release:
        types: published

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Check release from `master` branch
              run: |
                  ls -lsa
                  if [[ "${{ github.event.release.tag_name }}" != master* ]]; then
                    echo "Release not created from master. Workflow is aborted."
                    #exit 1 - Skipping for test
                  fi

            - name: Download latest release
              uses: robinraju/release-downloader@v1.10
              with:
                  latest: true
                  fileName: "*.tgz"
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "20.13.1"

            - name: Unpack latest release
              run: |
                  gunzip -c *.tgz | tar xvf -

            - name: Publish to GitHub Node.js package registry
              run: |
                  npm publish --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
